### ISSUE TITLE
Open Design Kit links aren't visible

### ISSUE THREAD

**Issue by toolness** [toolness/jess-portfolio#16]
The open design kit links to "try it" and "read the blogpost" aren't visible on the project detail page. This is because they are indented under the `featured_in:` section of the YAML, which makes Hugo think that they are describing metadata about `featured_in`, rather than their own separate section:

```yaml
featured_in:
  title: "the Creative Commons Summit"
  links:
    - title: "Try it"
      url: http://opendesignkit.org/
    - title: "Read the blogpost"
      url: https://bocoup.com/weblog/open-design-kit-a-toolkit-for-designing-with-distributed-collaborators
```

In other words, `links:` and its children need to be de-indented by two spaces.

@iamjessklein can you fix this?
